rtmp:
  push: 
    pushlist: 
      live/list: rtmp://localhost:1936/live/rtmp
# hdl:
#   pull:
#     pullhost: true
#     pulllist: 
#       - live/hdl: https://aiotcomm.com.cn/assets/meri_snow_mountain.mp4

